export const THEME_CHANGE = "THEME_CHANGE";
export const HISTORY_BACK_CLOSE_LOADING = "HISTORY_BACK_CLOSE_LOADING";

export const PAGE_LOADING = "PAGE_LOADING";
export const PAGE_PUSH_TAB = "PAGE_PUSH_TAB"
export const PAGE_REMOVE_TAB = "PAGE_REMOVE_TAB"
